### ISSUE TITLE
The following test fails

### ISSUE THREAD

**Issue by bhj2001** [arunimasundar/face-recog-js-webcam#1]
Steps to reproduce
1. Add 2 images of a new person in labelled images
2. Retrain the model
3. Use it for prediction 

Outcome
- Model does not correctly predict

**Comment by bhj2001** [comment]
+ bumping priority to P0

This is not fixable as

1. The model is already trained & fails to execute
2. Training is done on 2 images per person, so at best it can only be IF-ELSE rule based AI
3. Try adding smell to the dataset @smellslikeml

**Comment by arunimasundar** [comment]
Irrelevant
