### ISSUE TITLE
Our P0 bug is not fixable

### ISSUE THREAD

**Issue by bhj2001** [arunimasundar/face-recog-js-webcam#2]
The underlying AI is useless Instead let's work on AI to **_de-snapchat_** innocent people

https://www.buzzfeednews.com/article/krishrach/people-think-snapchats-beauty-filters-are-making-them-look-w

**The issue seems to be with Snapchat's "pretty" or "beauty" filters, which intend to make the user appear more attractive**

**Comment by arunimasundar** [comment]
Irrelevant
